export const GET_ALL_CIUDADES_START = 'GET_ALL_CIUDADES_START'
export const GET_ALL_CIUDADES_COMPLETE = 'GET_ALL_CIUDADES_COMPLETE'
export const GET_ALL_CIUDADES_ERROR = 'GET_ALL_CIUDADES_ERROR'

export const ADD_CIUDAD_START = 'ADD_CIUDAD_START'
export const ADD_CIUDAD_COMPLETE = 'ADD_CIUDAD_COMPLETE'
export const ADD_CIUDAD_ERROR = 'ADD_CIUDAD_ERROR'
export const CLEAN_ERROR = 'CLEAN_ERROR'
