export const GET_ALL_GRUPOS_START = 'GET_ALL_GRUPOS_START'
export const GET_ALL_GRUPOS_COMPLETE = 'GET_ALL_GRUPOS_COMPLETE'
export const GET_ALL_GRUPOS_ERROR = 'GET_ALL_GRUPOS_ERROR'

export const ADD_GRUPO_COMPLETE = 'ADD_GRUPO_COMPLETE'
export const ADD_GRUPO_ERROR = 'ADD_GRUPO_ERROR'
export const FORM_SERVER_ERROR = 'FORM_SERVER_ERROR'
export const CLEAN_ERROR = 'CLEAN_ERROR'
export const HANDLE_SUBMIT_GRUPO = 'HANDLE_SUBMIT_GRUPO'

export const EDIT_GRUPO_COMPLETE = 'EDIT_GRUPO_COMPLETE'
export const EDIT_GRUPO_ERROR = 'EDIT_GRUPO_ERROR'

export const DELETE_GRUPO_START = 'DELETE_GRUPO_START'
export const DELETE_GRUPO_COMPLETE = 'DELETE_GRUPO_COMPLETE'
export const DELETE_GRUPO_ERROR = 'DELETE_GRUPO_ERROR'