export const GET_ALL_PROFESORES_START = 'GET_ALL_PROFESORES_START'
export const GET_ALL_PROFESORES_COMPLETE = 'GET_ALL_PROFESORES_COMPLETE'
export const GET_ALL_PROFESORES_ERROR = 'GET_ALL_PROFESORES_ERROR'

export const ADD_PROFESOR_START = 'ADD_PROFESOR_START'
export const ADD_PROFESOR_COMPLETE = 'ADD_PROFESOR_COMPLETE'
export const ADD_PROFESOR_ERROR = 'ADD_PROFESOR_ERROR'
export const CLEAN_ERROR = 'CLEAN_ERROR'