export const GET_ALL_PROFESORES_START = 'GET_ALL_PROFESORES_START'
export const GET_ALL_PROFESORES_COMPLETE = 'GET_ALL_PROFESORES_COMPLETE'
export const GET_ALL_PROFESORES_ERROR = 'GET_ALL_PROFESORES_ERROR'
