export const GET_ALL_ESTUDIANTES_START = 'GET_ALL_ESTUDIANTES_START'
export const GET_ALL_ESTUDIANTES_COMPLETE = 'GET_ALL_ESTUDIANTES_COMPLETE'
export const GET_ALL_ESTUDIANTES_ERROR = 'GET_ALL_ESTUDIANTES_ERROR'

export const ADD_ESTUDIANTE_COMPLETE = 'ADD_ESTUDIANTE_COMPLETE'
export const ADD_ESTUDIANTE_ERROR = 'ADD_ESTUDIANTE_ERROR'
export const FORM_SERVER_ERROR = 'FORM_SERVER_ERROR'
export const CLEAN_ERROR = 'CLEAN_ERROR'
export const HANDLE_SUBMIT_ESTUDIANTE = 'HANDLE_SUBMIT_ESTUDIANTE'

export const EDIT_ESTUDIANTE_COMPLETE = 'EDIT_ESTUDIANTE_COMPLETE'
export const EDIT_ESTUDIANTE_ERROR = 'EDIT_ESTUDIANTE_ERROR'

export const DELETE_ESTUDIANTE_START = 'DELETE_ESTUDIANTE_START'
export const DELETE_ESTUDIANTE_COMPLETE = 'DELETE_ESTUDIANTE_COMPLETE'
export const DELETE_ESTUDIANTE_ERROR = 'DELETE_ESTUDIANTE_ERROR'